<?php
session_start();
if(!session_is_registered("email")){
header("location:login.php");
}
?>


<?php include 'includes/header.php' ?>
<?php include 'includes/connect.php'?>
<!-- Variables to seach for selected test -->
<?php

$evalid = ($_POST['evalid']);
?>

<?php $query= "SELECT testid, date_created FROM testgen WHERE evalid ='" .$evalid."'"; 

$result = mysql_query($query, $link)
		or die('You messed something up there are no results given' . mysql_error());
		
	echo " These are the test generated by $evalid <br />";	
	while($row1 = mysql_fetch_array($result)) {
	echo " <a href=retrieve.php?id=".$row1['testid'].">". $row1['date_created']. "  ". $row1['testid']. "</a> <br />";
	}
	
?> 

<div id="submit1">
    <a class="test2a" href="taskSelect.php">Return to Select Task.</a>
    <a class="test2a" href="logout.php">Logout</a>
    </div>
